# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQhfirB9hDnTglphOR1biutrXk2rD2lu
"""

import os
from flask import Flask, request, jsonify
import requests

app = Flask(__name__)

FRED_API_KEY = os.environ.get("FRED_API_KEY")
FRED_BASE_URL = "https://api.stlouisfed.org/fred"

def get_fred_observations(series_id, observation_start=None, observation_end=None):
    params = {
        "series_id": series_id,
        "api_key": FRED_API_KEY,
        "file_type": "json"
    }
    if observation_start:
        params["observation_start"] = observation_start
    if observation_end:
        params["observation_end"] = observation_end

    url = f"{FRED_BASE_URL}/series/observations"
    resp = requests.get(url, params=params)
    if resp.status_code == 200:
        return resp.json()
    else:
        return {"error": f"FRED API error: {resp.status_code} {resp.text}"}

@app.route("/")
def home():
    return "FRED API Demo: Use /observations?series_id=SERIES_ID"

@app.route("/observations")
def observations():
    series_id = request.args.get("series_id")
    observation_start = request.args.get("observation_start")
    observation_end = request.args.get("observation_end")
    if not series_id:
        return jsonify({"error": "series_id is required"}), 400
    data = get_fred_observations(series_id, observation_start, observation_end)
    return jsonify(data)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10000)