services:
  - type: web
    name: fred-api-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: FRED_API_KEY
        sync: false
    plan: free
